language: r
r:
  - oldrel
  - release
  - devel
cache: packages
os:
  - linux
  - osx
dist: xenial
jobs:
  exclude:
    - r: devel
      os: osx
r_packages:
  - covr
after_success:
  - Rscript -e "covr::codecov()"
